### ISSUE TITLE
About ts-morph getType / getJsxAttributeValue

### ISSUE THREAD

**Issue by astahmer** [itsdouges/TRIPLEX#9]
hey, I was randomly scrolling a [codesearch](https://cs.github.com/?scopeName=All+repos&scope=&q=ts-morph+.addAttribute%28%7B+name%3A+) and found your repo, the description got me curious and I started looking to find out what it was, and it looks cool ! can't wait to see the first preview

as I was wandering in the repo files, I stumbled upon the [`ts-morph/jsx.ts`](https://github.com/itsdouges/TRIPLEX/blob/main/packages/ts-morph/src/jsx.ts#L12) and it seems to me that you've also solved a problem I had, static extraction of JSX attributes, and also found something in your repo that caused performance issues in my side

I [used to also call `getType()`](https://github.com/astahmer/box-extractor/commit/950bb2e48060cf50ed7e280a4c2d58e438cdf050#diff-6811a255a1de2a9668a40701b63d060aecb6106442f9d4ecc5b98d29bd7790d5R34) as a kind of shortcut to get the types of a JsxAttribute and it turned out to be.. quite slow

so I added more cases till the `getType` was not needed anymore, I also can evaluate (using [ts-evaluator](https://github.com/wessberg/ts-evaluator)) partial AST nodes when needed to cover even more cases (like conditions branches or function calls)

anyway, as I don't have proper docs atm, you can scroll a bit on [this file](https://github.com/astahmer/box-extractor/blob/dbcde43a64b74192fc524bb29229084087445fb2/packages/box-extractor/tests/extract.test.ts) to see what box-extractor can extract (a lot tbh)

so I think [this `getJsxAttributeValue` method](https://github.com/itsdouges/TRIPLEX/blob/0f74022e8fcda91c6a8a677d3f9e299e9e0dae60/packages/ts-morph/src/jsx.ts#L12) could be replaced by box-extractor's `extractJsxAttributeIdentifierValue` (not exported as of now in the published package but I can do it now if you need it)

but you could also just replace https://github.com/itsdouges/TRIPLEX/blob/main/packages/server/src/index.ts#L93 by a complete component search with `extract({ component: ["Scene"] })` (if `Scene` is the actual component name, idk it's been a while since my last r3f project 😅 )
https://github.com/itsdouges/TRIPLEX/blob/main/packages/ts-morph/src/jsx.ts#L12

sorry for the long text & ofc it's fine if you don't want (or need) to use box-extractor, I just wanted to reach you in case you might and didn't know about it !

**Comment by itsdouges** [comment]
Hi, is this a human message? 😳

I'm using ts morph to extract JSX type information. Does your library have an api/package for that?

**Comment by astahmer** [comment]
yes this is a human message 😭 😭  I wanted to DM you on twitter at first but you have them closed so I thought here was fine

yes it does static extraction on both JSX attribute/spread & functions arguments ! you can install it with `pnpm i @box-extractor/core`, if you have any questions just @ me here or on twitter

**Comment by itsdouges** [comment]
Haha, no worries mate I've followed you on Twitter so we can DM if you'd like! I'll have to try it out sometime, right now I'm focusing on getting an MVP usable.
